# Generated by Django 4.0.8 on 2023-02-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35)),
                ('descricao', models.TextField(max_length=70, null=True)),
                ('entrada', models.BooleanField(default=True)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
            ],
        ),
    ]
