# Generated by Django 4.0.8 on 2023-02-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movimentacao', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=35)),
                ('data', models.DateField()),
                ('movimentacoes', models.ManyToManyField(to='movimentacao.movimentacao')),
            ],
        ),
    ]
